sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=alephdata/aleph-elasticsearch

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - echo "${TRAVIS_BRANCH}"
  - docker build -t "${IMAGE_NAME}:${TRAVIS_COMMIT}" .

script:
  - sleep 1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "${IMAGE_NAME}:${TRAVIS_COMMIT}"
