name: package

on: 
  push: {}
  schedule:
    - cron: "0 3 * * *"

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      # - name: Build docker image
      #   run: |
      #     docker build -t ghcr.io/alephdata/aleph-elasticsearch:${GITHUB_SHA} .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ghcr.io/alephdata/aleph-elasticsearch:${GITHUB_SHA}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/alephdata/aleph-elasticsearch:${{ github.sha }}
      # - name: Push docker image (hash)
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      #     docker push ghcr.io/alephdata/aleph-elasticsearch:${GITHUB_SHA}
