name: package

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        run: |
          docker build -t ghcr.io/alephdata/aleph-elasticsearch:${GITHUB_SHA} .
      - name: Push docker image (hash)
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/alephdata/aleph-elasticsearch:${GITHUB_SHA}
